#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "curl wrapper script to upload files to 0x0.st"
}

app_install() {
    local version="${1:-$(app_version)}"

    wget -O "$SDD_TEMP_DIR/$APP_NAME.tar.gz" \
        "https://github.com/Calinou/0x0/archive/master.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$APP_NAME".tar.gz

    cd "$SDD_TEMP_DIR/$APP_NAME-master" || exit 1

    app_remove

    install -vD -m755 "bin/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_commit_hash 'Calinou/0x0'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
