#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A port of the wildly popular helper application autojump to Rust"
}

app_install() {
    local version="${1:-$(app_version)}"

    # Override APP_NAME to autojump
    APP_NAME="autojump"

    local package="$APP_NAME-$version-$APP_ARCH-unknown-linux-musl"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/xen0n/autojump-rs/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    wget -O "$SDD_TEMP_DIR"/develop.tar.gz \
        "https://github.com/xen0n/autojump-rs/archive/develop.tar.gz"
    utils:extract "$SDD_TEMP_DIR"/develop.tar.gz

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install integrations
    cd "$SDD_TEMP_DIR/autojump-rs-develop" || exit 1

    install -vD -m644 "integrations/autojump.sh" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.sh" >&2

    install -vD -m644 "integrations/autojump.bash" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.bash" >&2

    install -vD -m644 "integrations/autojump.fish" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.fish" >&2

    install -vD -m644 "integrations/autojump.tcsh" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.tcsh" >&2

    install -vD -m644 "integrations/autojump.zsh" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.zsh" >&2

    # Install zsh completion
    install -vD -m644 "integrations/_j" "$SDD_ZSH_COMPLETION_DIR/_j" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_j" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.sh" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.bash" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.fish" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.tcsh" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/autojump/autojump.zsh" >&2
}

app_version() {
    utils:github_latest_release 'xen0n/autojump-rs'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
