#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Terminal bandwidth utilization tool"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-v${version}-$APP_ARCH-unknown-linux-musl"

    # Override the package name for specific version
    case "$version" in
    v*)
        package="$APP_NAME-${version}-$APP_ARCH-unknown-linux-musl"
        ;;
    esac

    utils:get_file \
        "https://github.com/imsnif/bandwhich/releases/download/$version/$package".tar.gz \
        "$SDD_TEMP_DIR/$package".tar.gz
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    if utils:compare_versions "${version#v}" lt "0.22.0"; then
        utils:get_file \
            "https://github.com/imsnif/bandwhich/archive/$version.tar.gz" \
            "$SDD_TEMP_DIR/$version.tar.gz"
        utils:extract "$SDD_TEMP_DIR/$version".tar.gz

        cd "$SDD_TEMP_DIR/${APP_NAME}-${version#v}" || exit 1
    fi

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    if utils:compare_versions "${version#v}" lt "0.22.0"; then
        # Install man page
        install -vD -m644 "docs/$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2

        # Install bash completion
        install -vD -m644 "completion/$APP_NAME" \
            "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    fi

    cat <<POST_INSTALL_MSG
$APP_NAME: To allow run $APP_NAME without root permission, please set the file capabilities manually:
$APP_NAME: sudo setcap 'cap_sys_ptrace,cap_dac_read_search,cap_net_raw,cap_net_admin+ep' "$SDD_BIN_DIR/$APP_NAME"
POST_INSTALL_MSG
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'imsnif/bandwhich'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
