#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Terminal bandwidth utilization tool"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-v${version}-$APP_ARCH-unknown-linux-musl"

    # Override the package name for specific version
    case "$version" in
    v*)
        package="$APP_NAME-${version}-$APP_ARCH-unknown-linux-musl"
        ;;
    esac

    wget -O "$SDD_TEMP_DIR/$package".tar.gz \
        "https://github.com/imsnif/bandwhich/releases/download/$version/$package".tar.gz
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'imsnif/bandwhich'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
