#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Resource monitor that shows usage and stats"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-${version#v}"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/aristocratos/bashtop/archive/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Copy themes
    mkdir -vp "${XDG_CONFIG_HOME:-$HOME/.config}/$APP_NAME/themes" >&2
    cp -v themes/* "${XDG_CONFIG_HOME:-$HOME/.config}/$APP_NAME/themes" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_tag 'aristocratos/bashtop'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
