#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Yet another cross-platform graphical process/system monitor"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${APP_ARCH}-unknown-linux-gnu"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/clementtsang/bottom/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/btm" "$SDD_BIN_DIR/btm" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/btm" >&2
}

app_version() {
    utils:github_latest_release 'clementtsang/bottom'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
