#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A new way to see and navigate directory trees"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version#v}.zip"

    wget -O "$SDD_TEMP_DIR/$package" \
        "https://github.com/Canop/broot/releases/download/$version/$package"
    utils:extract "$SDD_TEMP_DIR/$package"

    cd "$SDD_TEMP_DIR" || exit 1

    app_remove

    install -vD -m755 "$APP_ARCH-linux/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install man page
    install -vD -m644 "$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2

    # Install bash completions
    install -vD -m644 "completion/$APP_NAME.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    install -vD -m644 "completion/br.bash" "$SDD_BASH_COMPLETION_DIR/br" >&2

    # Install zsh completions
    install -vD -m644 "completion/_$APP_NAME" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
    install -vD -m644 "completion/_br" "$SDD_ZSH_COMPLETION_DIR/_br" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/br" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_br" >&2
}

app_version() {
    utils:github_latest_release 'Canop/broot'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
