#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "The shell-like, command line terminal file manager"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-${version#v}-linux-$APP_ARCH"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/leo-arch/clifm/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR" || exit 1

    app_remove

    install -vD -m755 "bin/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/$APP_NAME"
    cp -r --preserve=mode -- files/* "${XDG_CONFIG_HOME:-$HOME/.config}/$APP_NAME"

    # Install man page
    install -vD -m644 "$APP_NAME.1.gz" "$SDD_MAN_DIR/man1/$APP_NAME.1.gz" >&2

    # Install bash completion
    install -vD -m644 "completions.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    # Install zsh completion
    install -vD -m644 "completions.zsh" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1.gz"
}

app_version() {
    utils:github_latest_release 'leo-arch/clifm'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
