#!/usr/bin/env bash

set -euo pipefail

APP_URL="https://github.com/bcicen/ctop"
APP_DESC="Top-like interface for container metrics"

app_info() {
    utils:info
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}-${version#v}-linux-amd64"

    utils:get_file \
        "$APP_URL/releases/download/$version/$package" \
        "$SDD_TEMP_DIR/$APP_NAME"
    
    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release "${APP_URL#https://github.com/}"
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
