#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Query, update and convert data structures from the command line"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_linux_amd64"

    utils:get_file \
        "https://github.com/TomWright/dasel/releases/download/$version/$package" \
        "$SDD_TEMP_DIR/$APP_NAME"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'TomWright/dasel'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
