#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A syntax-highlighter for git and diff output"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-$version-arm-unknown-linux-gnueabihf"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/dandavison/delta/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$package/$APP_NAME" \
        "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'dandavison/delta'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
