#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Make your diffs human readable instead of machine readable"
}

app_install() {
    local version="${1:-$(app_version)}"

    wget -O "$SDD_TEMP_DIR/$APP_NAME" \
        "https://raw.githubusercontent.com/so-fancy/diff-so-fancy/$version/third_party/build_fatpack/diff-so-fancy"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'so-fancy/diff-so-fancy'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
