#!/usr/bin/env bash

set -euo pipefail

declare -a _DISTROBOX_BINS=(
    distrobox
    distrobox-assemble
    distrobox-create
    distrobox-enter
    distrobox-ephemeral
    distrobox-export
    distrobox-generate-entry
    distrobox-host-exec
    distrobox-init
    distrobox-list
    distrobox-rm
    distrobox-stop
    distrobox-upgrade
)

declare -a _DISTROBOX_COMP=(
    distrobox
    distrobox-assemble
    distrobox-create
    distrobox-enter
    distrobox-ephemeral
    distrobox-generate-entry
    distrobox-list
    distrobox-rm
    distrobox-stop
    distrobox-upgrade
)

declare -a _DISTROBOX_MANS=(
    distrobox.1
    distrobox-assemble.1
    distrobox-compatibility.1
    distrobox-create.1
    distrobox-enter.1
    distrobox-ephemeral.1
    distrobox-export.1
    distrobox-generate-entry.1
    distrobox-host-exec.1
    distrobox-init.1
    distrobox-list.1
    distrobox-rm.1
    distrobox-stop.1
    distrobox-upgrade.1
)

app_info() {
    utils:info "Use any linux distribution inside your terminal"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-${version#v}"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/89luca89/distrobox/archive/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    # Install bins
    for bin in "${_DISTROBOX_BINS[@]}"; do
        [ -f "$bin" ] || continue
        install -vD -m755 "$bin" "$SDD_BIN_DIR/$bin" >&2 || true
    done

    # Install bash completions
    for comp in "${_DISTROBOX_COMP[@]}"; do
        [ -f "completions/$comp" ] || continue
        install -vD -m644 "completions/$comp" "$SDD_BASH_COMPLETION_DIR/$comp" >&2
    done

    # Install man pages
    for manpage in "${_DISTROBOX_MANS[@]}"; do
        [ -f "man/man1/$manpage" ] || continue
        install -vD -m644 "man/man1/$manpage" "$SDD_MAN_DIR/man1/$manpage" >&2
    done
}

app_remove() {
    # Remove bins
    for bin in "${_DISTROBOX_BINS[@]}"; do
        rm -vf "$SDD_BIN_DIR/$bin" >&2
    done

    # Remove bash completions
    for comp in "${_DISTROBOX_COMP[@]}"; do
        rm -vf "$SDD_BASH_COMPLETION_DIR/$comp" >&2
    done

    # Remove man pages
    for manpage in "${_DISTROBOX_MANS[@]}"; do
        rm -vf "$SDD_MAN_DIR/man1/$manpage" >&2
    done
}

app_version() {
    utils:github_latest_release '89luca89/distrobox'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
