#!/usr/bin/env bash

set -euo pipefail

APP_URL="https://github.com/docker/compose"
APP_DESC="Define and run multi-container applications with Docker"

app_info() {
    utils:info
}

app_install() {
    local version="${1:-$(app_version)}"

    utils:get_file \
        "$APP_URL/releases/download/$version/$APP_NAME-linux-$APP_ARCH" \
        "$SDD_TEMP_DIR/$APP_NAME"
    
    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release "${APP_URL#https://github.com/}"
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
