#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A Docker credential helper for GCR users"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_linux_amd64-${version#v}"

    wget -O "$SDD_TEMP_DIR/$APP_NAME.tar.gz" \
        "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$APP_NAME".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'GoogleCloudPlatform/docker-credential-gcr'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
