#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Lets you install Docker Engine on virtual hosts"
}

app_install() {
    local version="${1:-$(app_version)}"

    utils:get_file \
        "https://github.com/docker/machine/releases/download/$version/$APP_NAME-Linux-$APP_ARCH" \
        "$SDD_TEMP_DIR/$APP_NAME"

    utils:get_file \
        "https://github.com/docker/machine/archive/$version.tar.gz" \
        "$SDD_TEMP_DIR/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    cd "$SDD_TEMP_DIR/${APP_NAME#docker-}-${version#v}" || exit 1

    install -vD -m644 "contrib/completion/bash/$APP_NAME.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    install -vD -m644 "contrib/completion/zsh/_$APP_NAME" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'docker/machine'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
