#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "a better 'df' alternative"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version#v}_linux_${APP_ARCH}"

    utils:get_file \
        "https://github.com/muesli/duf/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    utils:get_file \
        "https://github.com/muesli/duf/archive/$version.tar.gz" \
        "$SDD_TEMP_DIR/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    # Install fzf binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1

    # Install man page
    install -vD -m644 "$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
}

app_version() {
    utils:github_latest_release 'muesli/duf'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
