#!/usr/bin/env bash

set -euo pipefail

APP_URL="https://github.com/elio-fm/elio"
APP_DESC="Snappy, batteries-included terminal file manager"

app_info() {
    utils:info
}

app_install() {
    local version="${1:-$(app_version)}"
    local package=$APP_NAME-${version#v}-$APP_ARCH-unknown-linux-gnu

    utils:get_file \
        "$APP_URL/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz "
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz "
    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Copy launcher
    install -vD -m644 "packaging/linux/$APP_NAME.desktop" \
        "${XDG_HOME_DATA:-$HOME/.local/share}/applications/$APP_NAME.desktop" >&2

    # Copy icons
    for s in 48x48 128x128 256x256 512x512; do
        icon_file="packaging/linux/icons/hicolor/$s/apps/$APP_NAME.png"
        [ -f "$icon_file" ] || continue
        install -vD -m644 "$icon_file" \
            "${XDG_HOME_DATA:-$HOME/.local/share}/icons/hicolor/$s/apps/$APP_NAME.png" >&2
    done
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "${XDG_HOME_DATA:-$HOME/.local/share}/applications/$APP_NAME.desktop" >&2
    rm -vf "${XDG_HOME_DATA:-$HOME/.local/share}/icons/hicolor/"??x??"/apps/$APP_NAME.png" >&2
    rm -vf "${XDG_HOME_DATA:-$HOME/.local/share}/icons/hicolor/"???x???"/apps/$APP_NAME.png" >&2
}

app_version() {
    utils:github_latest_tag "${APP_URL#https://github.com/}"
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
