#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A modern version of 'ls'"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-linux-$APP_ARCH-${version#v}.zip"

    wget -O "$SDD_TEMP_DIR/$package" \
        "https://github.com/ogham/exa/releases/download/$version/$package"
    utils:extract "$SDD_TEMP_DIR/$package"

    wget -O "$SDD_TEMP_DIR/$version.tar.gz" \
        "https://github.com/ogham/exa/archive/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME-linux-$APP_ARCH" \
        "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1

    install -vD -m644 "contrib/man/$APP_NAME.1" \
        "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2

    install -vD -m644 "contrib/completions.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    install -vD -m644 "contrib/completions.zsh" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'ogham/exa'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
