#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A modern version of 'ls'"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-linux-$APP_ARCH-$version.zip"

    wget -O "$SDD_TEMP_DIR/$package" \
        "https://github.com/ogham/exa/releases/download/$version/$package"
    utils:extract "$SDD_TEMP_DIR/$package"

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/bin/$APP_NAME" \
        "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    install -vD -m644 "$SDD_TEMP_DIR/man/$APP_NAME.1" \
        "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2

    install -vD -m644 "$SDD_TEMP_DIR/man/${APP_NAME}_colors.5" \
        "$SDD_MAN_DIR/man5/$APP_NAME.5" >&2

    install -vD -m644 "$SDD_TEMP_DIR/completions/$APP_NAME.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    install -vD -m644 "$SDD_TEMP_DIR/completions/$APP_NAME.zsh" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_MAN_DIR/man5/${APP_NAME}_colors.5" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'ogham/exa'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
