#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A modern, maintained replacement for 'ls'"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${APP_ARCH}-unknown-linux-gnu"
    local _version="${version#v}"

    utils:get_file \
        "https://github.com/eza-community/eza/releases/download/$version/$package".tar.gz \
        "$SDD_TEMP_DIR/$package".tar.gz
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" \
        "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    if utils:compare_versions "$_version" ge "0.18.13"; then
        utils:get_file \
            "https://github.com/eza-community/eza/releases/download/$version/completions-$_version".tar.gz \
            "$SDD_TEMP_DIR/completions-$_version".tar.gz
        utils:extract "$SDD_TEMP_DIR/completions-$_version".tar.gz

        utils:get_file \
            "https://github.com/eza-community/eza/releases/download/$version/man-$_version".tar.gz \
            "$SDD_TEMP_DIR/man-$_version".tar.gz
        utils:extract "$SDD_TEMP_DIR/man-$_version".tar.gz

        install -vD -m644 "$SDD_TEMP_DIR/target/completions-$_version/$APP_NAME" \
            "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

        install -vD -m644 "$SDD_TEMP_DIR/target/completions-$_version/_$APP_NAME" \
            "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2

        # Install man page
        install -vD -m644 "$SDD_TEMP_DIR/target/man-$_version/$APP_NAME.1" \
            "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2

        install -vD -m644 "$SDD_TEMP_DIR/target/man-$_version/${APP_NAME}_colors.5" \
            "$SDD_MAN_DIR/man5/${APP_NAME}_colors.5" >&2

        install -vD -m644 "$SDD_TEMP_DIR/target/man-$_version/${APP_NAME}_colors-explanation.5" \
            "$SDD_MAN_DIR/man5/${APP_NAME}_colors-explanation.5" >&2
    fi
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_MAN_DIR/man5/${APP_NAME}_colors.5" >&2
    rm -vf "$SDD_MAN_DIR/man5/${APP_NAME}_colors-explanation.5" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'eza-community/eza'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
