#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "command-line tool for batch renaming files and directories quickly and safely"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version#v}_linux_amd64"

    utils:get_file \
        "https://github.com/ayoisaiah/f2/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'ayoisaiah/f2'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
