#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A simple file manager written in bash"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-${version#v}"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/dylanaraps/fff/archive/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
    install -vD -m644 "$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
}

app_version() {
    utils:github_latest_release 'dylanaraps/fff'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
