#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A fully featured Firefox Send client"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-$version-linux-x64-static"

    wget -O "$SDD_TEMP_DIR/$APP_NAME" \
        "https://github.com/timvisee/ffsend/releases/download/$version/$package"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'timvisee/ffsend'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
