#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A command-line fuzzy finder"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-${version#v}-linux_amd64"

    utils:get_file \
        "https://github.com/junegunn/fzf/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    utils:get_file \
        "https://github.com/junegunn/fzf/archive/$version.tar.gz" \
        "$SDD_TEMP_DIR/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    # Install fzf binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1

    install -vD -m755 "bin/$APP_NAME-tmux" "$SDD_BIN_DIR/$APP_NAME-tmux" >&2

    install -vD -m644 "man/man1/$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    install -vD -m644 "man/man1/$APP_NAME-tmux.1" \
        "$SDD_MAN_DIR/man1/$APP_NAME-tmux.1" >&2

    install -vD -m644 "shell/completion.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    install -vD -m644 "shell/completion.zsh" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2

    install -vD -m644 "shell/key-bindings.bash" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/fzf/shell/key-bindings.bash" >&2

    install -vD -m644 "shell/key-bindings.zsh" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/fzf/shell/key-bindings.zsh" >&2

    install -vD -m644 "plugin/$APP_NAME.vim" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/plugin/$APP_NAME.vim" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BIN_DIR/$APP_NAME-tmux" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME-tmux.1" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/fzf/shell/key-bindings.bash" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/fzf/shell/key-bindings.zsh" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/plugin/$APP_NAME.vim" >&2
}

app_version() {
    utils:github_latest_release 'junegunn/fzf'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
