#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Pretty fast disk usage analyzer written in Go"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_linux_amd64"

    wget -O "$SDD_TEMP_DIR/$package.tgz" \
        "https://github.com/dundee/gdu/releases/download/$version/$package.tgz"
    utils:extract "$SDD_TEMP_DIR/$package".tgz

    wget -O "$SDD_TEMP_DIR/$version.tar.gz" \
        "https://github.com/dundee/gdu/archive/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$package" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1

    install -vD -m644 "$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'dundee/gdu'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
