#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "The GitHub CLI tool"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version#[vV]}_linux_386"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/cli/cli/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    install -vD -m755 "bin/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install man pages
    mkdir -vp "$SDD_MAN_DIR/man1/" >&2
    cp -v "share/man/man1/$APP_NAME"*.1 "$SDD_MAN_DIR"/man1 >&2

    # Generate shell completions
    "$SDD_BIN_DIR/$APP_NAME" completion -s bash > \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME"

    "$SDD_BIN_DIR/$APP_NAME" completion -s zsh > \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME"
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME"*.1 >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'cli/cli'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
