#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "distributed, offline-first bug tracker embedded in git, with bridges"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_linux_amd64"

    wget -O "$SDD_TEMP_DIR/$APP_NAME" \
        "https://github.com/MichaelMure/git-bug/releases/download/$version/$package"

    wget -O "$SDD_TEMP_DIR/$version.tar.gz" \
        "https://github.com/MichaelMure/git-bug/archive/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    cd "$SDD_TEMP_DIR/$APP_NAME-$version" || exit 1

    # Install man page
    mkdir -vp "$SDD_MAN_DIR/man1/" >&2
    cp -v doc/man/*.1 "$SDD_BIN_DIR"/share/man/man1 >&2

    install -vD -m644 "misc/bash_completion/$APP_NAME" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    install -vD -m644 "misc/zsh_completion/$APP_NAME" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME"*.1 >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'MichaelMure/git-bug'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
