#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Blazing fast terminal-ui for git written in rust"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-linux-${APP_ARCH}"

    # Change the package name for version under v0.26
    if utils:compare_versions "${version#v}" lt "0.26"; then
        package="$APP_NAME-linux-musl"
    fi

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/extrawurst/gitui/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'extrawurst/gitui'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
