#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Manage your GnuPG keys with ease!"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}-${version#v}-${APP_ARCH}-unknown-linux-gnu"

    utils:get_file \
        "https://github.com/orhun/gpg-tui/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    install -vD -m644 "man/$APP_NAME.1" \
        "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2

    # Install bash completion
    install -vD -m644 "completions/$APP_NAME.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    # Install zsh completion
    install -vD -m644 "completions/_$APP_NAME" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'orhun/gpg-tui'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
