#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Make JSON greppable!"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-linux-amd64-${version#v}"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/tomnomnom/gron/releases/download/$version/$package.tgz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    # get latest pre-release
    utils:github_releases 'tomnomnom/gron' | head -1
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
