#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A tool for glamorous shell scripts"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version#v}_Linux_${APP_ARCH}"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/charmbracelet/gum/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    # Add subdirectory to path for v0.14.0 and newer
    if utils:compare_versions "${version#v}" ge "0.14.0"; then
        cd "$SDD_TEMP_DIR/$package" || exit 1
    else
        # for v0.13.0 and older
        cd "$SDD_TEMP_DIR" || exit 1
    fi

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install man page
    install -vD -m644 "manpages/$APP_NAME.1.gz" "$SDD_MAN_DIR/man1/$APP_NAME.1.gz" >&2

    # Install bash completion
    install -vD -m644 "completions/$APP_NAME.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    # Install zsh completion
    install -vD -m644 "completions/$APP_NAME.zsh" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1.gz" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'charmbracelet/gum'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
