#!/usr/bin/env bash

set -euo pipefail

ALT_APP_NAME="Hack"
SDD_FONTS_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/fonts"

app_info() {
    utils:info "A typeface designed for source code. Patched with Nerd Fonts iconics"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$ALT_APP_NAME-$version-ttf"

    wget -O "$SDD_TEMP_DIR/$version.tar.gz" \
        "https://github.com/source-foundry/Hack/releases/download/$version/$package".tar.gz
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    cd "$SDD_TEMP_DIR/ttf" || exit 1

    app_remove

    # Copy fonts
    mkdir -vp "$SDD_FONTS_HOME/$ALT_APP_NAME" >&2
    cp -v -- *.ttf "$SDD_FONTS_HOME/$ALT_APP_NAME/" >&2

    # Rebuild font cache
    if command -v fc-cache >/dev/null; then
        fc-cache -fv "$SDD_FONTS_HOME" >&2
    fi
}

app_remove() {
    rm -vf "$SDD_FONTS_HOME/$ALT_APP_NAME/"*.?tf >&2
    rmdir -v "$SDD_FONTS_HOME/$ALT_APP_NAME" >&2 || true

    # Rebuild font cache
    [ "$SDD_ACTION" == "install" ] && return 0
    if command -v fc-cache >/dev/null; then
        fc-cache -fv "$SDD_FONTS_HOME" >&2
    fi
}

app_version() {
    utils:github_latest_release 'source-foundry/Hack'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
