#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A tool for automated image compression"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-v${version##*/}-linux"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/imager-io/imager/releases/download/${version//\//%2F}/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/linux/bin/$APP_NAME" \
        "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_tags 'imager-io/imager' | head -1
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
