#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A powerful duplicate file finder and an enhanced fork of 'fdupes'"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}-${version#v}-linux-${APP_ARCH}"

    wget -O "$SDD_TEMP_DIR/$package.pkg.tar.xz" \
        "https://github.com/jbruchon/jdupes/releases/download/$version/$package.pkg.tar.xz"
    utils:extract "$SDD_TEMP_DIR/$package.pkg.tar.xz"

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'jbruchon/jdupes'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
