#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Open source note taking and to-do application with synchronization"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="Joplin-${version#v}.AppImage"

    wget -O "$SDD_TEMP_DIR/$APP_NAME" \
        "https://github.com/laurent22/joplin/releases/download/$version/$package"

    # download icons
    for size in 16x16 24x24 32x32 48x48 128x128 512x512; do
        wget -O "$SDD_TEMP_DIR/$APP_NAME-$size.png" \
            "https://raw.githubusercontent.com/laurent22/joplin/$version/Assets/LinuxIcons/$size.png"
    done

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # create launcher
    mkdir -vp "${XDG_HOME_DATA:-$HOME/.local/share}/applications" >&2
    cat > "${XDG_HOME_DATA:-$HOME/.local/share}/applications/$APP_NAME.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Joplin
GenericName=Secure Notebook
Comment=A free and secure notebook management application
Exec=${APP_NAME}
Icon=${APP_NAME}
Terminal=false
Categories=Network;Office;TextEditor;WordProcessor;X-Markdown;X-KaTeX;X-Mermaid;X-Fountain;X-E2EE;
Keywords=secure;security;privacy;private;notes;bookmarks;collaborate;research;
StartupWMClass=Joplin
StartupNotify=true
EOF

    # install icons
    for size in 16x16 24x24 32x32 48x48 128x128 512x512; do
        install -vD -m644 "$SDD_TEMP_DIR/$APP_NAME-$size.png" \
            "${XDG_HOME_DATA:-$HOME/.local/share}/icons/hicolor/$size/apps/$APP_NAME.png" >&2
    done
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "${XDG_HOME_DATA:-$HOME/.local/share}/applications/$APP_NAME.desktop"

    # remove icons
    for size in 16x16 24x24 32x32 48x48 128x128 512x512; do
        rm -vf "${XDG_HOME_DATA:-$HOME/.local/share}/icons/hicolor/$size/apps/$APP_NAME.png" >&2
    done
}

app_version() {
    utils:github_latest_release 'laurent22/joplin'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
