#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Jump helps you navigate faster by learning your habits"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_linux_amd64_binary"

    utils:get_file \
        "https://github.com/gsamokovarov/jump/releases/download/$version/$package" \
        "$SDD_TEMP_DIR/$APP_NAME"

    utils:get_file \
        "https://github.com/gsamokovarov/jump/archive/$version.tar.gz" \
        "$SDD_TEMP_DIR/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1

    install -vD -m644 "man/$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    install -vD -m644 "man/j.1" "$SDD_MAN_DIR/man1/j.1" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_MAN_DIR/man1/j.1" >&2
}

app_version() {
    utils:github_latest_release 'gsamokovarov/jump'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
