#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Just a command runner"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-$version-$APP_ARCH-unknown-linux-musl"

    utils:get_file \
        "https://github.com/casey/just/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    install -vD -m644 "$SDD_TEMP_DIR/$APP_NAME.1" \
        "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2

    # Install extras
    if utils:compare_versions "$version" lt "1.23.0"; then
        utils:get_file \
            "https://github.com/casey/just/archive/$version.tar.gz" \
            "$SDD_TEMP_DIR/$version.tar.gz"
        utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

        cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1
    else
        cd "$SDD_TEMP_DIR" || exit 1
    fi

    install -vD -m644 "completions/$APP_NAME.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    install -vD -m644 "completions/$APP_NAME.zsh" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'casey/just'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
