#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Improve keyboard comfort and usability with advanced customization"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package

    # Set the package name for specific version
    if utils:compare_versions "$version" le "v1.9.0"; then
        package="${APP_NAME}"
    elif utils:compare_versions "$version" ge "v1.10.1"; then
        package="${APP_NAME}-linux-binaries-${version}-x64.zip"
    else
        package="linux-binaries-x64-${version}.zip"
    fi

    utils:get_file \
        "https://github.com/jtroo/kanata/releases/download/$version/$package" \
        "$SDD_TEMP_DIR/$package"

    app_remove

    # Run install instruction for specific version
    if utils:compare_versions_alt "$version" le "v1.9.0"; then
        install -vD -m755 "$SDD_TEMP_DIR/$package" "$SDD_BIN_DIR/$APP_NAME" >&2
    else
        utils:extract "$SDD_TEMP_DIR/$package"
        install -vD -m755 "$SDD_TEMP_DIR/kanata_linux_cmd_allowed_x64" "$SDD_BIN_DIR/$APP_NAME" >&2
    fi
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'jtroo/kanata'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
