#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "An interactive TLS-capable intercepting HTTP proxy for software developers"
}

app_install() {
    local version="${1:-$(app_version)}"

    # Remove prefix from version
    version="${version#v}"

    local package="${APP_NAME}-${version}-linux"

    if utils:compare_versions "$version" ge "10.1.6"; then
        package="${APP_NAME}-${version}-linux-${APP_ARCH}"
    fi

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://snapshots.mitmproxy.org/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
    install -vD -m755 "$SDD_TEMP_DIR/mitmdump" "$SDD_BIN_DIR/mitmdump" >&2
    install -vD -m755 "$SDD_TEMP_DIR/mitmweb" "$SDD_BIN_DIR/mitmweb" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BIN_DIR/mitmdump" >&2
    rm -vf "$SDD_BIN_DIR/mitmweb" >&2
}

app_version() {
    utils:github_latest_release 'mitmproxy/mitmproxy'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
