#!/usr/bin/env bash

set -euo pipefail

APP_URL="https://github.com/hrkfdn/ncspot"
APP_DESC="Spotify client written in Rust, inspired by ncmpc and the likes"

app_info() {
    utils:info
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}-$version-linux-${APP_ARCH}.tar.gz"

    utils:get_file \
        "$APP_URL/releases/download/$version/$package" \
        "$SDD_TEMP_DIR/$package"
    utils:extract "$SDD_TEMP_DIR/$package"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release "${APP_URL#https://github.com/}"
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
