#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "helps you to find/fix obsolete Nerd Font icons in your project"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}-${APP_ARCH}-unknown-linux-musl"

    utils:get_file \
        "https://github.com/loichyan/nerdfix/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'loichyan/nerdfix'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
