#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "AI coding agent, built for the terminal"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package

    # Set the package name for specific version
    if utils:compare_versions "$version" le "v1.0.92"; then
        package="${APP_NAME}-linux-x64.zip"
    else
        package="${APP_NAME}-linux-x64.tar.gz"
    fi

    utils:get_file \
        "https://github.com/anomalyco/opencode/releases/download/$version/$package" \
        "$SDD_TEMP_DIR/$package"
    utils:extract "$SDD_TEMP_DIR/$package"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'anomalyco/opencode'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
