#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Universal markup converter"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-$version-linux-amd64"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/jgm/pandoc/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    cd "$SDD_TEMP_DIR/$APP_NAME-$version" || exit 1

    app_remove

    install -vD -m755 "bin/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install man page
    install -vD -m755 "share/man/man1/$APP_NAME.1.gz" \
        "$SDD_MAN_DIR/man1/$APP_NAME.1.gz" >&2

    # Install bash completion
    "$SDD_BIN_DIR/$APP_NAME" --bash-completion > \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME"
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1.gz" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'jgm/pandoc'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
