#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A command-line tool to generate, analyze, convert and manipulate colors"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}-${version}-${APP_ARCH}-unknown-linux-musl"

    utils:get_file \
        "https://github.com/sharkdp/pastel/releases/download/$version/$package".tar.gz \
        "$SDD_TEMP_DIR/$package".tar.gz
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    # Install binary
    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install bash completion
    install -vD -m644 "autocomplete/$APP_NAME.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    # Install zsh completion
    install -vD -m644 "autocomplete/_$APP_NAME" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'sharkdp/pastel'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
