#!/usr/bin/env bash

set -euo pipefail

APP_URL="https://github.com/peco/peco"
APP_DESC="Simplistic interactive filtering tool"

app_info() {
    utils:info
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version#v}_linux_amd64"

    # Set the package name for specific version
    if utils:compare_versions "$version" lt "v0.6.0"; then
        # don't include version into package name
        package="${APP_NAME}_linux_amd64"
    fi

    utils:get_file \
        "$APP_URL/releases/download/$version/$package".tar.gz \
        "$SDD_TEMP_DIR/$package".tar.gz
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    if utils:compare_versions "$version" lt "v0.6.0"; then
        cd "$SDD_TEMP_DIR/$package" || exit 1
    else
        cd "$SDD_TEMP_DIR" || exit 1
    fi

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release "${APP_URL#https://github.com/}"
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
