#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Podman Terminal UI"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-release-linux_amd64"

    utils:get_file \
        "https://github.com/containers/podman-tui/releases/download/$version/$package.zip" \
        "$SDD_TEMP_DIR/$package.zip"
    utils:extract "$SDD_TEMP_DIR/$package".zip

    app_remove

    cd "$SDD_TEMP_DIR/$package/$APP_NAME-${version#v}" || exit 1

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'containers/podman-tui'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
