#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Transfer files over wifi by scanning a QR code without leaving the terminal"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version}_linux_amd64.tar.gz"

    if utils:compare_versions "$version" le "0.10.1"; then
        package="${APP_NAME}_${version}_linux_${APP_ARCH}.tar.gz"
    fi

    utils:get_file \
        "https://github.com/claudiodangelis/qrcp/releases/download/$version/$package" \
        "$SDD_TEMP_DIR/$package"
    utils:extract "$SDD_TEMP_DIR/$package"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Generate shell completions
    mkdir -vp "$SDD_BASH_COMPLETION_DIR" >&2
    "$SDD_BIN_DIR/$APP_NAME" completion bash > \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME"

    mkdir -vp "$SDD_ZSH_COMPLETION_DIR" >&2
    "$SDD_BIN_DIR/$APP_NAME" completion zsh > \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME"
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'claudiodangelis/qrcp'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
