#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "rsync for cloud storage"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}-${version}-linux-amd64"

    wget -O "$SDD_TEMP_DIR/$package".zip \
        "https://github.com/rclone/rclone/releases/download/$version/$package".zip
    utils:extract "$SDD_TEMP_DIR/$package".zip

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    # Install binary
    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install man page
    install -vD -m644 "$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2

    # Generate shell completions
    mkdir -vp "$SDD_BASH_COMPLETION_DIR" >&2
    "$SDD_BIN_DIR/$APP_NAME" completion bash > \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME"

    mkdir -vp "$SDD_ZSH_COMPLETION_DIR" >&2
    "$SDD_BIN_DIR/$APP_NAME" completion zsh > \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME"
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME"*.1 >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'rclone/rclone'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
