#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Fast, secure, efficient backup program"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version#v}_linux_amd64"

    utils:get_file \
        "https://github.com/restic/restic/releases/download/$version/$package".bz2 \
        "$SDD_TEMP_DIR/$package".bz2
    utils:extract "$SDD_TEMP_DIR/$package".bz2

    utils:get_file \
        "https://github.com/restic/restic/archive/$version.tar.gz" \
        "$SDD_TEMP_DIR/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$package" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1

    for i in "doc/man/$APP_NAME"*.1; do
        manpage="${i##*/}"
        install -vD -m644 "doc/man/$manpage" \
            "$SDD_MAN_DIR/man1/$manpage" >&2
    done

    install -vD -m644 "doc/bash-completion.sh" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    install -vD -m644 "doc/zsh-completion.zsh" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME"*.1 >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'restic/restic'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
