#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "a CLI application to render static SVG files"
}

app_install() {
    local version="${1:-$(app_version)}"

    local package="$APP_NAME-linux-$APP_ARCH"

    utils:get_file \
        "https://github.com/linebender/resvg/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'linebender/resvg'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
