#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Open a file with a program specified in the mailcap"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="mailcap-${version}"

    utils:get_file \
        "https://salsa.debian.org/debian/mailcap/-/archive/${version/-/\/}/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    install -vD -m644 "$APP_NAME.man" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
}

app_version() {
    utils:gitlab_latest_tag 'debian/mailcap' 'salsa.debian.org' |
        sed 's/%2F/-/'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
