#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A simple terminal UI for search and replace, ala VS Code"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-$version-linux-$APP_ARCH"

    utils:get_file \
        "https://github.com/yassinebridi/serpl/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'yassinebridi/serpl'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
