#!/usr/bin/env bash

set -euo pipefail

ALT_APP_NAME="sk"

app_info() {
    utils:info "Fuzzy Finder in rust!"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-$version-$APP_ARCH-unknown-linux-musl"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/lotabout/skim/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    wget -O "$SDD_TEMP_DIR/$version.tar.gz" \
        "https://github.com/lotabout/skim/archive/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    # Install sk binary
    install -vD -m755 "$SDD_TEMP_DIR/$ALT_APP_NAME" \
        "$SDD_BIN_DIR/$ALT_APP_NAME" >&2

    # Install extras
    cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1

    install -vD -m755 "bin/$ALT_APP_NAME-tmux" \
        "$SDD_BIN_DIR/$ALT_APP_NAME-tmux" >&2

    install -vD -m644 "man/man1/$ALT_APP_NAME.1" \
        "$SDD_MAN_DIR/man1/$ALT_APP_NAME.1" >&2
    install -vD -m644 "man/man1/$ALT_APP_NAME-tmux.1" \
        "$SDD_MAN_DIR/man1/$ALT_APP_NAME-tmux.1" >&2

    install -vD -m644 "shell/completion.bash" \
        "$SDD_BASH_COMPLETION_DIR/$ALT_APP_NAME" >&2

    install -vD -m644 "shell/completion.zsh" \
        "$SDD_ZSH_COMPLETION_DIR/_$ALT_APP_NAME" >&2

    install -vD -m644 "shell/key-bindings.bash" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/$ALT_APP_NAME/shell/key-bindings.bash" >&2

    install -vD -m644 "shell/key-bindings.zsh" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/$ALT_APP_NAME/shell/key-bindings.zsh" >&2

    install -vD -m644 "plugin/$APP_NAME.vim" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/plugin/$APP_NAME.vim" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$ALT_APP_NAME" >&2
    rm -vf "$SDD_BIN_DIR/$ALT_APP_NAME-tmux" >&2
    rm -vf "$SDD_MAN_DIR/man1/$ALT_APP_NAME.1" >&2
    rm -vf "$SDD_MAN_DIR/man1/$ALT_APP_NAME-tmux.1" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$ALT_APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$ALT_APP_NAME" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/$ALT_APP_NAME/shell/key-bindings.bash" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/$ALT_APP_NAME/shell/key-bindings.zsh" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/plugin/$APP_NAME.vim" >&2
}

app_version() {
    utils:github_latest_release 'lotabout/skim'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
