#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "creates an interactive selection window at the cursor location"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package

	case "${version#v}" in
		1.3.0)
			package="$APP_NAME-${version#v}-linux-musl-${APP_ARCH/x/s}-static"
			;;
		*)
			package="$APP_NAME-${version#v}-linux-musl-$APP_ARCH-static"
			;;
	esac

    wget -O "$SDD_TEMP_DIR/$package".xz \
        "https://github.com/p-gen/smenu/releases/download/$version/$package".xz
    utils:extract "$SDD_TEMP_DIR/$package".xz

    wget -O "$SDD_TEMP_DIR/$version.tar.gz" \
        "https://github.com/p-gen/smenu/archive/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$package" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    cd "$SDD_TEMP_DIR/$APP_NAME-${version#v}" || exit 1

    install -vD -m644 "$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
}

app_version() {
    utils:github_latest_release 'p-gen/smenu'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
