#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Snippet CLI manager for quickly accessing shell snippets"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version#v}_linux_amd64"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/lemoony/snipkit/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Generate shell completions
    "$SDD_BIN_DIR/$APP_NAME" completion bash > \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME"

    "$SDD_BIN_DIR/$APP_NAME" completion zsh > \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME"
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'lemoony/snipkit'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
