#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Terminal client for Spotify"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}_${version#v}_Linux_${APP_ARCH}"

    wget -O "$SDD_TEMP_DIR/$package.tar.gz" \
        "https://github.com/jbszczepaniak/spotify-cli/releases/download/$version/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    cd "$SDD_TEMP_DIR" || exit 1

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'jbszczepaniak/spotify-cli'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
