#!/usr/bin/env bash

set -euo pipefail

ALT_APP_NAME="spf"

app_info() {
    utils:info "Pretty fancy and modern terminal file manager"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}-linux-${version}-amd64"

    utils:get_file \
        "https://github.com/yorukot/superfile/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package.tar.gz"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/dist/$package/$ALT_APP_NAME" \
        "$SDD_BIN_DIR/$ALT_APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$ALT_APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'yorukot/superfile'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
