#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Open Source Continuous File Synchronization"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-linux-amd64-$version"

    utils:get_file \
        "https://github.com/syncthing/syncthing/releases/download/$version/$package.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install launchers
    install -vD -m644 "etc/linux-desktop/$APP_NAME-ui.desktop" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/applications/$APP_NAME-ui.desktop" >&2
    install -vD -m644 "etc/linux-desktop/$APP_NAME-start.desktop" \
        "${XDG_DATA_HOME:-$HOME/.local/share}/applications/$APP_NAME-start.desktop" >&2

    # Install systemd service
    install -vD -m644 "etc/linux-systemd/user/$APP_NAME.service" \
        "${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/$APP_NAME.service" >&2

    cat <<POST_INSTALL_MSG
$APP_NAME: Execute to enable and start the $APP_NAME service:
$APP_NAME: systemctl --user enable --now $APP_NAME.service
$APP_NAME: See https://docs.syncthing.net/users/autostart.html#how-to-set-up-a-user-service
POST_INSTALL_MSG
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/applications/$APP_NAME-ui.desktop" >&2
    rm -vf "${XDG_DATA_HOME:-$HOME/.local/share}/applications/$APP_NAME-start.desktop" >&2
    rm -vf "${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/$APP_NAME.service" >&2
}

app_version() {
    utils:github_latest_release 'syncthing/syncthing'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
