#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "An fzf terminal UI for systemctl"
}

app_install() {
    local version="${1:-$(app_version)}"

    utils:get_file \
        "https://github.com/joehillen/sysz/releases/download/${version#v}/$APP_NAME" \
        "$SDD_TEMP_DIR/$APP_NAME"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'joehillen/sysz'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
