#!/usr/bin/env bash

set -euo pipefail

APP_URL="https://github.com/cytopia/linux-timemachine"
APP_DESC="Rsync-based OSX-like time machine"

app_info() {
    utils:info
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="linux-$APP_NAME-${version#v}"

    utils:get_file \
        "$APP_URL/archive/$version.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release "${APP_URL#https://github.com/}"
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
