#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "CLI client for images compressing using tinypng.com API"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-linux-amd64"

    wget -O "$SDD_TEMP_DIR/$APP_NAME" \
        "https://github.com/tarampampam/tinifier/releases/download/$version/$package"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'tarampampam/tinifier'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
