#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "Golang command line client for tldr"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-linux-amd64"

    wget -O "$SDD_TEMP_DIR/$package" \
        "https://github.com/mstruebing/tldr/releases/download/$version/$package"

    wget -O "$SDD_TEMP_DIR/$version.tar.gz" \
        "https://github.com/mstruebing/tldr/archive/$version.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$version.tar.gz"

    app_remove

    # Install binary
    install -vD -m755 "$SDD_TEMP_DIR/$package" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install extras
    cd "$SDD_TEMP_DIR/$APP_NAME-$version" || exit 1

    install -vD -m644 "autocompletion/autocomplete.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    install -vD -m644 "autocompletion/autocomplete.zsh" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'mstruebing/tldr'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
