#!/usr/bin/env bash

set -euo pipefail

APP_URL="https://github.com/thameera/vimv"
APP_DESC="Batch-rename files using Vim"

app_info() {
    utils:info
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-master"

    utils:get_file \
        "$APP_URL/archive/master.tar.gz" \
        "$SDD_TEMP_DIR/$package.tar.gz"
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR/$package" || exit 1

    app_remove

    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_commit_hash "${APP_URL#https://github.com/}"
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
