#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "like top or htop but with zoom-able charts, network, and disk usage"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="${APP_NAME}.${APP_ARCH}-unknown-linux-musl"

    if utils:compare_versions "$version" ge "0.14.2"; then
        package="${APP_NAME}-Linux-musl-${APP_ARCH}.tar.gz"
    else
        package="${APP_NAME}.${APP_ARCH}-unknown-linux-musl.tgz"
    fi

    utils:get_file \
        "https://github.com/bvaisvil/zenith/releases/download/$version/$package" \
        "$SDD_TEMP_DIR/$package"
    utils:extract "$SDD_TEMP_DIR/$package"

    app_remove

    install -vD -m755 "$SDD_TEMP_DIR/$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'bvaisvil/zenith'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
