#!/usr/bin/env bash

set -euo pipefail

app_info() {
    utils:info "A smarter cd command"
}

app_install() {
    local version="${1:-$(app_version)}"
    local package="$APP_NAME-${version#v}-$APP_ARCH-unknown-linux-musl"

    wget -O "$SDD_TEMP_DIR/$package".tar.gz \
        "https://github.com/ajeetdsouza/zoxide/releases/download/$version/$package".tar.gz
    utils:extract "$SDD_TEMP_DIR/$package".tar.gz

    cd "$SDD_TEMP_DIR" || exit 1

    app_remove

    # Install binary
    install -vD -m755 "$APP_NAME" "$SDD_BIN_DIR/$APP_NAME" >&2

    # Install man pages
    install -vD -m644 "man/man1/$APP_NAME.1" "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    install -vD -m644 "man/man1/zoxide-remove.1" "$SDD_MAN_DIR/man1/zoxide-remove.1" >&2
    install -vD -m644 "man/man1/zoxide-add.1" "$SDD_MAN_DIR/man1/zoxide-add.1" >&2
    install -vD -m644 "man/man1/zoxide-import.1" "$SDD_MAN_DIR/man1/zoxide-import.1" >&2
    install -vD -m644 "man/man1/zoxide-query.1" "$SDD_MAN_DIR/man1/zoxide-query.1" >&2
    install -vD -m644 "man/man1/zoxide-init.1" "$SDD_MAN_DIR/man1/zoxide-init.1" >&2

    install -vD -m644 "completions/$APP_NAME.bash" \
        "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2

    install -vD -m644 "completions/_$APP_NAME" \
        "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_remove() {
    rm -vf "$SDD_BIN_DIR/$APP_NAME" >&2
    rm -vf "$SDD_MAN_DIR/man1/$APP_NAME.1" >&2
    rm -vf "$SDD_MAN_DIR/man1/zoxide-remove.1" >&2
    rm -vf "$SDD_MAN_DIR/man1/zoxide-add.1" >&2
    rm -vf "$SDD_MAN_DIR/man1/zoxide-import.1" >&2
    rm -vf "$SDD_MAN_DIR/man1/zoxide-query.1" >&2
    rm -vf "$SDD_MAN_DIR/man1/zoxide-init.1" >&2
    rm -vf "$SDD_BASH_COMPLETION_DIR/$APP_NAME" >&2
    rm -vf "$SDD_ZSH_COMPLETION_DIR/_$APP_NAME" >&2
}

app_version() {
    utils:github_latest_release 'ajeetdsouza/zoxide'
}

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")"

# shellcheck source=./_utils.sh
source "$SCRIPT_DIR/_utils.sh"

utils:parser "$@"
